// AUTO-GENERATED by scripts/optimize-photos.mjs — do not edit by hand.
// Re-run the script to regenerate. Add titles/locations via PHOTO_META in lib/data.ts.
import type { Photo } from "./types";

export const GENERATED_PHOTOS: Photo[] = [
  {
    "src": "/photography/02.jpg",
    "width": 2000,
    "height": 1330,
    "camera": "Nikon D3200",
    "lens": "55.0-200.0 mm f/4.0-5.6",
    "settings": "f/13 · 1/800s · ISO 100 · 85mm",
    "year": "2012"
  },
  {
    "src": "/photography/03.jpg",
    "width": 2000,
    "height": 1330,
    "camera": "Nikon D3200",
    "lens": "55.0-200.0 mm f/4.0-5.6",
    "settings": "f/8 · 1/60s · ISO 400 · 102mm",
    "year": "2012"
  },
  {
    "src": "/photography/04.jpg",
    "width": 1330,
    "height": 2000,
    "camera": "Nikon D3200",
    "lens": "55.0-200.0 mm f/4.0-5.6",
    "settings": "f/10 · 1/400s · ISO 100 · 55mm",
    "year": "2011"
  },
  {
    "src": "/photography/05.jpg",
    "width": 2000,
    "height": 1330,
    "camera": "Nikon D3200",
    "lens": "55.0-200.0 mm f/4.0-5.6",
    "settings": "f/4.2 · 1/1250s · ISO 100 · 86mm",
    "year": "2011"
  },
  {
    "src": "/photography/06.jpg",
    "width": 2000,
    "height": 1330,
    "camera": "Nikon D3200",
    "lens": "55.0-200.0 mm f/4.0-5.6",
    "settings": "f/10 · 1/200s · ISO 100 · 170mm",
    "year": "2011"
  },
  {
    "src": "/photography/07.jpg",
    "width": 1330,
    "height": 2000,
    "camera": "Nikon D3200",
    "lens": "55.0-200.0 mm f/4.0-5.6",
    "settings": "f/5.6 · 1/125s · ISO 110 · 55mm",
    "year": "2011"
  },
  {
    "src": "/photography/08.jpg",
    "width": 2000,
    "height": 1330,
    "camera": "Nikon D3200",
    "lens": "55.0-200.0 mm f/4.0-5.6",
    "settings": "f/5.6 · 1/250s · ISO 400 · 200mm",
    "year": "2011"
  },
  {
    "src": "/photography/09.jpg",
    "width": 2000,
    "height": 1330,
    "camera": "Nikon D3200",
    "lens": "55.0-200.0 mm f/4.0-5.6",
    "settings": "f/8 · 1/250s · ISO 100 · 92mm",
    "year": "2011"
  },
  {
    "src": "/photography/10.jpg",
    "width": 1330,
    "height": 2000,
    "camera": "Nikon D3200",
    "lens": "55.0-200.0 mm f/4.0-5.6",
    "settings": "f/5.6 · 1/125s · ISO 100 · 55mm",
    "year": "2011"
  },
  {
    "src": "/photography/12.jpg",
    "width": 1500,
    "height": 2000,
    "camera": "Apple iPhone 17 Pro",
    "lens": "iPhone 17 Pro back triple camera 16.8906mm f/2.79883",
    "settings": "f/2.8 · 1/640s · ISO 32 · 17mm",
    "year": "2025"
  },
  {
    "src": "/photography/13.jpg",
    "width": 1500,
    "height": 2000,
    "camera": "Apple iPhone 17 Pro",
    "lens": "iPhone 17 Pro back triple camera 16.8906mm f/2.79883",
    "settings": "f/2.8 · 1/120s · ISO 250 · 17mm",
    "year": "2025"
  },
  {
    "src": "/photography/14.jpg",
    "width": 2000,
    "height": 1500,
    "camera": "Apple iPhone 17 Pro",
    "lens": "iPhone 17 Pro back triple camera 16.8906mm f/2.79883",
    "settings": "f/2.8 · 1/120s · ISO 100 · 17mm",
    "year": "2025"
  },
  {
    "src": "/photography/15.jpg",
    "width": 1500,
    "height": 2000,
    "camera": "Apple iPhone 16 Pro",
    "lens": "iPhone 16 Pro back triple camera 15.66mm f/2.8",
    "settings": "f/2.8 · 1/3200s · ISO 50 · 16mm",
    "year": "2025"
  },
  {
    "src": "/photography/16.jpg",
    "width": 1500,
    "height": 2000,
    "camera": "Apple iPhone 17 Pro",
    "lens": "iPhone 17 Pro back triple camera 16.8906mm f/2.79883",
    "settings": "f/2.8 · 1/90s · ISO 500 · 17mm",
    "year": "2025"
  },
  {
    "src": "/photography/17.jpg",
    "width": 2000,
    "height": 1500,
    "camera": "Apple iPhone 16 Pro",
    "lens": "iPhone 16 Pro back triple camera 15.66mm f/2.8",
    "settings": "f/2.8 · 1/210s · ISO 50 · 16mm",
    "year": "2025"
  },
  {
    "src": "/photography/18.jpg",
    "width": 1500,
    "height": 2000,
    "camera": "Apple iPhone 15 Pro",
    "lens": "iPhone 15 Pro back triple camera 9mm f/2.8",
    "settings": "f/2.8 · 1/3400s · ISO 20 · 9mm",
    "year": "2024"
  },
  {
    "src": "/photography/19.jpg",
    "width": 1500,
    "height": 2000,
    "camera": "Apple iPhone 16 Pro",
    "lens": "iPhone 16 Pro back triple camera 6.765mm f/1.78",
    "settings": "f/1.8 · 1/2300s · ISO 64 · 7mm",
    "year": "2025"
  },
  {
    "src": "/photography/20.jpg",
    "width": 1500,
    "height": 2000,
    "camera": "Apple iPhone 16 Pro",
    "lens": "iPhone 16 Pro back triple camera 6.765mm f/1.78",
    "settings": "f/1.8 · 1/6700s · ISO 100 · 7mm",
    "year": "2024"
  },
  {
    "src": "/photography/21.jpg",
    "width": 1500,
    "height": 2000,
    "camera": "Apple iPhone 17 Pro",
    "lens": "iPhone 17 Pro back triple camera 16.891mm f/2.8",
    "settings": "f/2.8 · 1/12800s · ISO 20 · 17mm",
    "year": "2026"
  },
  {
    "src": "/photography/22.jpg",
    "width": 1500,
    "height": 2000,
    "camera": "Apple iPhone 16 Pro",
    "lens": "iPhone 16 Pro back triple camera 6.765mm f/1.78",
    "settings": "f/1.8 · 1/11400s · ISO 50 · 7mm",
    "year": "2025"
  },
  {
    "src": "/photography/23.jpg",
    "width": 2000,
    "height": 1330,
    "camera": "Nikon D3200",
    "lens": "55.0-200.0 mm f/4.0-5.6",
    "settings": "f/5.6 · 1/500s · ISO 110 · 200mm",
    "year": "2011"
  },
  {
    "src": "/photography/24.jpg",
    "width": 2000,
    "height": 1330,
    "camera": "Nikon D3200",
    "lens": "55.0-200.0 mm f/4.0-5.6",
    "settings": "f/11 · 1/500s · ISO 100 · 55mm",
    "year": "2011"
  },
  {
    "src": "/photography/25.jpg",
    "width": 1330,
    "height": 2000,
    "camera": "Nikon D3200",
    "lens": "55.0-200.0 mm f/4.0-5.6",
    "settings": "f/5.6 · 1/200s · ISO 100 · 190mm",
    "year": "2011"
  },
  {
    "src": "/photography/26.jpg",
    "width": 2000,
    "height": 1330,
    "camera": "Nikon D3200",
    "lens": "55.0-200.0 mm f/4.0-5.6",
    "settings": "f/4.5 · 1/1250s · ISO 100 · 102mm",
    "year": "2011"
  },
  {
    "src": "/photography/27.jpg",
    "width": 2000,
    "height": 1500,
    "camera": "Apple iPhone 17 Pro",
    "lens": "iPhone 17 Pro back triple camera 16.891mm f/2.8",
    "settings": "f/2.8 · 1/640s · ISO 25 · 17mm",
    "year": "2026"
  },
  {
    "src": "/photography/28.jpg",
    "width": 2000,
    "height": 1330,
    "camera": "Nikon D3200",
    "lens": "55.0-200.0 mm f/4.0-5.6",
    "settings": "f/10 · 1/200s · ISO 100 · 200mm",
    "year": "2011"
  },
  {
    "src": "/photography/29.jpg",
    "width": 1500,
    "height": 2000,
    "camera": "Apple iPhone 17 Pro",
    "lens": "iPhone 17 Pro back triple camera 16.891mm f/2.8",
    "settings": "f/2.8 · 1/350s · ISO 50 · 17mm",
    "year": "2026"
  },
  {
    "src": "/photography/30.jpg",
    "width": 1500,
    "height": 2000,
    "camera": "Apple iPhone 16 Pro",
    "lens": "iPhone 16 Pro back triple camera 15.66mm f/2.8",
    "settings": "f/2.8 · 1/320s · ISO 64 · 16mm",
    "year": "2025"
  },
  {
    "src": "/photography/31.jpg",
    "width": 2000,
    "height": 1500,
    "camera": "Apple iPhone 16 Pro",
    "lens": "iPhone 16 Pro back triple camera 6.765mm f/1.78",
    "settings": "f/1.8 · 10s · ISO 2500 · 7mm",
    "year": "2025"
  },
  {
    "src": "/photography/32.jpg",
    "width": 1500,
    "height": 2000,
    "camera": "Apple iPhone 17 Pro",
    "lens": "iPhone 17 Pro back triple camera 16.891mm f/2.8",
    "settings": "f/2.8 · 1/800s · ISO 20 · 17mm",
    "year": "2026"
  },
  {
    "src": "/photography/33.jpg",
    "width": 1500,
    "height": 2000,
    "camera": "Apple iPhone 17 Pro",
    "lens": "iPhone 17 Pro back triple camera 16.891mm f/2.8",
    "settings": "f/2.8 · 1/640s · ISO 40 · 17mm",
    "year": "2026"
  },
  {
    "src": "/photography/34.jpg",
    "width": 1500,
    "height": 2000,
    "camera": "Apple iPhone 17 Pro",
    "lens": "iPhone 17 Pro back triple camera 16.891mm f/2.8",
    "settings": "f/2.8 · 1/8000s · ISO 16 · 17mm",
    "year": "2026"
  },
  {
    "src": "/photography/35.jpg",
    "width": 1500,
    "height": 2000,
    "camera": "Apple iPhone 16 Pro",
    "lens": "iPhone 16 Pro back triple camera 15.66mm f/2.8",
    "settings": "f/2.8 · 1/2900s · ISO 64 · 16mm",
    "year": "2025"
  },
  {
    "src": "/photography/36.jpg",
    "width": 1500,
    "height": 2000,
    "camera": "Apple iPhone 17 Pro",
    "lens": "iPhone 17 Pro back triple camera 6.765mm f/1.78",
    "settings": "f/1.8 · 1/2s · ISO 2000 · 7mm",
    "year": "2026"
  },
  {
    "src": "/photography/37.jpg",
    "width": 1500,
    "height": 2000,
    "camera": "Apple iPhone 16 Pro",
    "lens": "iPhone 16 Pro back triple camera 15.66mm f/2.8",
    "settings": "f/2.8 · 1/5000s · ISO 40 · 16mm",
    "year": "2025"
  },
  {
    "src": "/photography/38.jpg",
    "width": 1500,
    "height": 2000
  },
  {
    "src": "/photography/39.jpg",
    "width": 1500,
    "height": 2000,
    "camera": "Apple iPhone 17 Pro",
    "lens": "iPhone 17 Pro back triple camera 6.765mm f/1.78",
    "settings": "f/1.8 · 1/1900s · ISO 64 · 7mm",
    "year": "2025"
  },
  {
    "src": "/photography/40.jpg",
    "width": 1500,
    "height": 2000,
    "camera": "Apple iPhone 17 Pro",
    "lens": "iPhone 17 Pro back triple camera 6.765mm f/1.78",
    "settings": "f/1.8 · 1/400s · ISO 64 · 7mm",
    "year": "2025"
  },
  {
    "src": "/photography/41.jpg",
    "width": 1500,
    "height": 2000,
    "camera": "Apple iPhone 17 Pro",
    "lens": "iPhone 17 Pro back triple camera 6.765mm f/1.78",
    "settings": "f/1.8 · 1/400s · ISO 64 · 7mm",
    "year": "2025"
  },
  {
    "src": "/photography/42.jpg",
    "width": 1500,
    "height": 2000,
    "camera": "Apple iPhone 17 Pro",
    "lens": "iPhone 17 Pro back triple camera 6.765mm f/1.78",
    "settings": "f/1.8 · 1/400s · ISO 64 · 7mm",
    "year": "2025"
  },
  {
    "src": "/photography/43.jpg",
    "width": 1500,
    "height": 2000,
    "camera": "Apple iPhone 17 Pro",
    "lens": "iPhone 17 Pro back triple camera 6.765mm f/1.78",
    "settings": "f/1.8 · 1/400s · ISO 64 · 7mm",
    "year": "2025"
  },
  {
    "src": "/photography/44.jpg",
    "width": 1500,
    "height": 2000,
    "camera": "Apple iPhone 17 Pro",
    "lens": "iPhone 17 Pro back triple camera 6.765mm f/1.78",
    "settings": "f/1.8 · 1/400s · ISO 64 · 7mm",
    "year": "2025"
  },
  {
    "src": "/photography/45.jpg",
    "width": 1500,
    "height": 2000,
    "camera": "Apple iPhone 17 Pro",
    "lens": "iPhone 17 Pro back triple camera 6.765mm f/1.78",
    "settings": "f/1.8 · 1/400s · ISO 64 · 7mm",
    "year": "2025"
  },
  {
    "src": "/photography/46.jpg",
    "width": 1125,
    "height": 2000,
    "camera": "Apple iPhone 17 Pro",
    "lens": "iPhone 17 Pro back triple camera 6.765mm f/1.78",
    "settings": "f/1.8 · 1/400s · ISO 64 · 7mm",
    "year": "2025"
  },
  {
    "src": "/photography/47.jpg",
    "width": 1500,
    "height": 2000,
    "camera": "Apple iPhone 17 Pro",
    "lens": "iPhone 17 Pro back triple camera 6.765mm f/1.78",
    "settings": "f/1.8 · 1/400s · ISO 64 · 7mm",
    "year": "2025"
  },
  {
    "src": "/photography/48.jpg",
    "width": 1500,
    "height": 2000,
    "camera": "Apple iPhone 17 Pro",
    "lens": "iPhone 17 Pro back triple camera 6.765mm f/1.78",
    "settings": "f/1.8 · 1/400s · ISO 64 · 7mm",
    "year": "2025"
  },
  {
    "src": "/photography/49.jpg",
    "width": 1500,
    "height": 2000,
    "camera": "Apple iPhone 17 Pro",
    "lens": "iPhone 17 Pro back triple camera 6.765mm f/1.78",
    "settings": "f/1.8 · 1/400s · ISO 64 · 7mm",
    "year": "2025"
  },
  {
    "src": "/photography/50.jpg",
    "width": 2000,
    "height": 1500,
    "camera": "Apple iPhone 16 Pro",
    "lens": "iPhone 16 Pro back triple camera 15.66mm f/2.8",
    "settings": "f/2.8 · 1/1114s · ISO 64 · 16mm",
    "year": "2025"
  },
  {
    "src": "/photography/51.jpg",
    "width": 2000,
    "height": 1500,
    "camera": "Apple iPhone 16 Pro",
    "lens": "iPhone 16 Pro back triple camera 6.765mm f/1.78",
    "settings": "f/1.8 · 1/2205s · ISO 100 · 7mm",
    "year": "2025"
  },
  {
    "src": "/photography/52.jpg",
    "width": 1500,
    "height": 2000,
    "camera": "Apple iPhone 16 Pro",
    "lens": "iPhone 16 Pro back triple camera 6.765mm f/1.78",
    "settings": "f/1.8 · 1/11364s · ISO 80 · 7mm",
    "year": "2025"
  },
  {
    "src": "/photography/53.jpg",
    "width": 1500,
    "height": 2000,
    "camera": "Apple iPhone 16 Pro",
    "lens": "iPhone 16 Pro back triple camera 6.765mm f/1.78",
    "settings": "f/1.8 · 1/376s · ISO 64 · 7mm",
    "year": "2025"
  },
  {
    "src": "/photography/54.jpg",
    "width": 1500,
    "height": 2000
  },
  {
    "src": "/photography/55.jpg",
    "width": 2000,
    "height": 1500,
    "camera": "Apple iPhone 16 Pro",
    "lens": "iPhone 16 Pro back triple camera 15.66mm f/2.8",
    "settings": "f/2.8 · 1/260s · ISO 50 · 16mm",
    "year": "2025"
  },
  {
    "src": "/photography/56.jpg",
    "width": 1500,
    "height": 2000
  },
  {
    "src": "/photography/57.jpg",
    "width": 1500,
    "height": 2000
  },
  {
    "src": "/photography/58.jpg",
    "width": 2000,
    "height": 1500,
    "camera": "Apple iPhone 16 Pro",
    "lens": "iPhone 16 Pro back triple camera 15.66mm f/2.8",
    "settings": "f/2.8 · 1/1700s · ISO 64 · 16mm",
    "year": "2025"
  },
  {
    "src": "/photography/59.jpg",
    "width": 1500,
    "height": 2000,
    "camera": "Apple iPhone 16 Pro",
    "lens": "iPhone 16 Pro back triple camera 15.66mm f/2.8",
    "settings": "f/2.8 · 1/1689s · ISO 50 · 16mm",
    "year": "2025"
  },
  {
    "src": "/photography/60.jpg",
    "width": 1500,
    "height": 2000,
    "camera": "Apple iPhone 16 Pro",
    "lens": "iPhone 16 Pro back triple camera 15.66mm f/2.8",
    "settings": "f/2.8 · 1/1395s · ISO 50 · 16mm",
    "year": "2025"
  },
  {
    "src": "/photography/61.jpg",
    "width": 1500,
    "height": 2000
  },
  {
    "src": "/photography/62.jpg",
    "width": 1500,
    "height": 2000
  },
  {
    "src": "/photography/63.jpg",
    "width": 2000,
    "height": 1500
  },
  {
    "src": "/photography/64.jpg",
    "width": 1500,
    "height": 2000,
    "camera": "Apple iPhone 16 Pro",
    "lens": "iPhone 16 Pro back triple camera 15.66mm f/2.8",
    "settings": "f/2.8 · 1/4975s · ISO 40 · 16mm",
    "year": "2025"
  },
  {
    "src": "/photography/65.jpg",
    "width": 1500,
    "height": 2000
  },
  {
    "src": "/photography/66.jpg",
    "width": 1500,
    "height": 2000
  },
  {
    "src": "/photography/67.jpg",
    "width": 1500,
    "height": 2000
  },
  {
    "src": "/photography/68.jpg",
    "width": 1500,
    "height": 2000
  },
  {
    "src": "/photography/69.jpg",
    "width": 1500,
    "height": 2000
  },
  {
    "src": "/photography/70.jpg",
    "width": 1500,
    "height": 2000
  },
  {
    "src": "/photography/71.jpg",
    "width": 1500,
    "height": 2000
  }
];
