// Photo pipeline: read originals from photo-src/, auto-orient + resize + compress
// into public/photography/, pull EXIF, and emit lib/photos.generated.ts.
//
//   node scripts/optimize-photos.mjs
//
// Re-run any time you add/replace originals in photo-src/. Originals are NOT
// deployed (photo-src/ is gitignored); only the optimized files ship.
import { readdir, mkdir, writeFile, stat } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";
import exifr from "exifr";

const ROOT = path.resolve(import.meta.dirname, "..");
const SRC = path.join(ROOT, "photo-src");
const OUT = path.join(ROOT, "public", "photography");
const MANIFEST = path.join(ROOT, "lib", "photos.generated.ts");

const LONG_EDGE = 2000; // px, long side
const QUALITY = 80;

const isImg = (f) => /\.(jpe?g|png)$/i.test(f);
const num = (n, d = 0) => (typeof n === "number" ? +n.toFixed(d) : undefined);

// "1/250s" for fast shutter, "2s" for long exposure
function shutter(exposure) {
  if (!exposure) return undefined;
  return exposure < 1 ? `1/${Math.round(1 / exposure)}s` : `${num(exposure, 1)}s`;
}

function settingsLine(x) {
  const parts = [
    x.FNumber ? `f/${num(x.FNumber, 1)}` : null,
    shutter(x.ExposureTime),
    x.ISO ? `ISO ${x.ISO}` : null,
    x.FocalLength ? `${Math.round(x.FocalLength)}mm` : null,
  ].filter(Boolean);
  return parts.length ? parts.join(" · ") : undefined;
}

// Title-case ALL-CAPS brand words ("NIKON" -> "Nikon") but leave mixed case
// ("iPhone") and alphanumerics ("D3200") alone.
const tidy = (s) => s.replace(/\b[A-Z]{3,}\b/g, (w) => w[0] + w.slice(1).toLowerCase());

function cameraName(x) {
  const make = (x.Make || "").trim();
  const model = (x.Model || "").trim();
  if (!make && !model) return undefined;
  const makeWord = make.split(/\s+/)[0] || "";
  // If the model already names the brand, drop the (often noisy) Make field.
  const full = model.toLowerCase().includes(makeWord.toLowerCase())
    ? model
    : [makeWord, model].filter(Boolean).join(" ");
  return tidy(full) || undefined;
}

async function run() {
  await mkdir(OUT, { recursive: true });
  const files = (await readdir(SRC)).filter(isImg).sort((a, b) =>
    a.localeCompare(b, undefined, { numeric: true }),
  );
  if (!files.length) {
    console.error("No images in photo-src/");
    process.exit(1);
  }

  const photos = [];
  let inBytes = 0;
  let outBytes = 0;

  for (const file of files) {
    const inPath = path.join(SRC, file);
    inBytes += (await stat(inPath)).size;

    // normalize output name: 02.JPG -> 02.jpg
    const base = file.replace(/\.[^.]+$/, "").toLowerCase();
    const outName = `${base}.jpg`;
    const outPath = path.join(OUT, outName);

    let exif = {};
    try {
      exif = (await exifr.parse(inPath)) || {};
    } catch {
      /* no/!readable EXIF — fine */
    }

    // .rotate() with no args bakes in EXIF orientation, so width/height below
    // are the true display dimensions (portrait stays portrait).
    const { data, info } = await sharp(inPath)
      .rotate()
      .resize(LONG_EDGE, LONG_EDGE, { fit: "inside", withoutEnlargement: true })
      .jpeg({ quality: QUALITY, mozjpeg: true })
      .toBuffer({ resolveWithObject: true });

    await writeFile(outPath, data);
    outBytes += info.size;

    const year = exif.DateTimeOriginal
      ? new Date(exif.DateTimeOriginal).getFullYear().toString()
      : undefined;

    photos.push({
      src: `/photography/${outName}`,
      width: info.width,
      height: info.height,
      camera: cameraName(exif),
      lens: (exif.LensModel || "").trim() || undefined,
      settings: settingsLine(exif),
      year,
    });

    process.stdout.write(
      `${outName}  ${info.width}x${info.height}  ${(info.size / 1024).toFixed(0)}KB\n`,
    );
  }

  const body =
    "// AUTO-GENERATED by scripts/optimize-photos.mjs — do not edit by hand.\n" +
    "// Re-run the script to regenerate. Add titles/locations via PHOTO_META in lib/data.ts.\n" +
    'import type { Photo } from "./types";\n\n' +
    "export const GENERATED_PHOTOS: Photo[] = " +
    JSON.stringify(photos, null, 2) +
    ";\n";
  await writeFile(MANIFEST, body);

  const mb = (b) => (b / 1048576).toFixed(1);
  console.log(
    `\n${photos.length} photos · ${mb(inBytes)}MB -> ${mb(outBytes)}MB ` +
      `(${(100 - (outBytes / inBytes) * 100).toFixed(0)}% smaller)`,
  );
  console.log(`manifest: ${path.relative(ROOT, MANIFEST)}`);
}

run().catch((e) => {
  console.error(e);
  process.exit(1);
});
